.travis.yml
README.md
src/Channel.cpp
src/ChannelImpl.cpp
src/SimpleAmqpClient/ChannelImpl.h
testing/test_consume.cpp

The RabbitMQ broker changed the meaning of the global flag in the basic.qos
method in v3.2.0. (See: http://www.rabbitmq.com/consumer-prefetch.html)
Note that this fix needs some additional work to not break those using older versions of RabbitMQ.

Set basic.qos.global = true to match broker behavior change.

---

src/SimpleAmqpClient/ChannelImpl.h

Consumer prefetch was enabled in v3.3.0 and not v3.2.0 in the RabbitMQ broker.

Consumer prefetch enabled in RabbitMQ v3.3.0

---

CMakeLists.txt

Fixes issue #107. 
Just reverting part of commit https://github.com/alanxz/SimpleAmqpClient/commit/431a8ce70b9ccc591736c493455cfbdda33eefb1.
Was tested on VS2015.

CMake: fix MSVC build. add link to ws2_32.lib

---

src/TableImpl.cpp

This change fixes [issue #123](https://github.com/alanxz/SimpleAmqpClient/issues/123).

Treat a timestamp as an uint64_t

---

src/Channel.cpp
src/SimpleAmqpClient/Channel.h

Hi!
Our team currently maintains an internal version of `SimpleAmqpClient` with a "patch" which essentially boils down to what I'm sending here.
In one paragraph, we need to integrate RabbitMQ consumers with other network services (servers and clients) so that they run together in a single process. This is typically done via the event loop a.k.a. reactor pattern; to get that to work, we must have a way to obtain every connection's file descriptor (FD).
This team is not really that familiar with Open Source and shies away from contributing. So what they did was just package up a version of the library which **includes `ChannelImpl.h`** in the published/installable header set; and use that in their apps to obtain the file descriptor through direct access to `m_impl->m_connection`. As anyone …

Wrap amqp_get_sockfd() to expose the connection socket FD

---

CMakeLists.txt

While Debian and derivatives put 64bit libraries (and pkgconfig files)
in `/usr/lib`, Fedora and derivatives put 64bit libraries in
`/usr/lib64`.
We add compatibility for both by using cmake's GNUInstallDirs set of
variables instead of hardcoded references to "lib" and "bin".
This fix has been ported from 2.4.0 and was deployed to make 2.4.0 run smoothly under CentOS7 within a custom RPM package, it has not been tested under other distros nor Windows so, while it should not cause issues I believe this would warrant some tests in debian-based deployments.

Use portable cmake system paths

---

src/Channel.cpp
src/SimpleAmqpClient/Channel.h

It can be useful to verify the peer certificate without verifying the host name.

Add separate option for verify peer and verify host.

---

src/Channel.cpp

Fixes https://github.com/alanxz/SimpleAmqpClient/issues/238
Compilation without SSL support is broken due to wrong method signature.
Bug comes from https://github.com/alanxz/SimpleAmqpClient/commit/56713c06e273a4869332391164eed8a0f7137cac commit.

compilation fix

---

CMakeLists.txt
src/Channel.cpp
src/SimpleAmqpClient/MessageRejectedException.h
testing/test_channels.cpp

This effectively adds support for the broker to reject messages when a
queue is full. See https://www.rabbitmq.com/maxlength.html for an exmple
use case.
Fixes #215
Fixes #245
Fixes #216

lib: add support for rejected message in publish

---

.travis.yml
CMakeLists.txt
src/Table.cpp
testing/test_table.cpp

* Update to supported linux distribution (xenial)
* Add workaround for boost v1.58.0 brokenness with variant
* Make CMake specify c++98 as a standard when building

CI improvements

---

.travis.yml

This was likely broken in the upgrade from trusty -> xenial.

ci: fix travis to correctly run RabbitMQ

---

src/BasicMessage.cpp
src/Channel.cpp
src/ChannelImpl.cpp
src/SimpleAmqpClient/BasicMessage.h
src/SimpleAmqpClient/Channel.h
testing/test_message.cpp

This makes BasicMessage more value-type like, and removes forward
references to rabbitmq-c structs from the public API.
As a side-effect most accessor functions now return const-ref, which is
likely more efficient in most cases, though may cause an unexpected
behavior changes depending on how the API is used.

lib: refactor BasicMessage removing rabbitmq-c API

---

src/SimpleAmqpClient/Table.h
src/SimpleAmqpClient/TableImpl.h
src/Table.cpp
src/TableImpl.cpp
testing/test_table.cpp

uint64_t table values aren't supported by RabbitMQ: they cause
connection errors in older versions of RabbitMQ, and newer brokers
silently convert them to int64_t.
Timestamps are still represented using uin64_t, so this adds an API that
supports setting Timestamps. The interface is a bit different as
std::time_t is a typedef of another integral type and will conflict with
other overloads in existing overload sets.

lib: add support for table timestamp values & remove broken support for uint64 values.

---

.travis.yml

msan is a bit more involved in that it requires building boost and libc++ under memory santizier, so its a bit more involved to get setup.

Add asan/lsan/ubsan and tsan builds to travis

---

CMakeLists.txt

Include was mistakenly removed due to bad merge, this restores that.
Fixed: #265
Fixed: #266

build: restore GNUInstallDirs include (#265, #266)

---

src/SimpleAmqpClient/Channel.h
src/SimpleAmqpClient/Util.h

These are being replaced by the Channel::Open function and all new
functionality will be added there.
The deprecated functions will be removed in a future version.

lib: Mark Channel::Create* functions as deprecated

---

CMakeLists.txt
src/Channel.cpp
src/SimpleAmqpClient/Bytes.h

The latter is somewhat more efficient as it doesn't need to call strlen,
thus its O(1) instead of O(N) on string size.

lib: switch to StringToBytes from amqp_cstring_bytes

---

src/Channel.cpp

We cannot just replace the entire `ret._flags` variable when setting certain message properties. We need to OR the variable with the corresponding flag. Otherwise, setting e.g. message expiration resets all the previously set flags, such as for priority or delivery mode. Many flags are ORed correctly (e.g. priority or delivery mode), but some are not. This PR fixes that.
The bug that this PR fixes was introduced in commit 938b102f8fc85e5113b3e55700b8af9b71d9f01d.

Fix setting of flags in CreateAmqpProperties()

---

src/Channel.cpp

Hi @alanxz. Thanks for all the good work.
This PR should resolve:
- https://github.com/alanxz/SimpleAmqpClient/issues/178
- https://github.com/alanxz/SimpleAmqpClient/issues/294
- https://github.com/alanxz/SimpleAmqpClient/issues/295
There are all requiring the same thing - to optionally skip the call to the c library `amqp_ssl_socket_set_cacert`
I've tested it locally with no problems.
Kind regards,
Paul

Optionally set ca cert path

---

CMakeLists.txt

* Accounting for spaces in library paths
* Ignore debug and optimized CMake hints.

Yet another minor fixes missed in #337

---

CMakeLists.txt
libSimpleAmqpClient.pc.in
src/SimpleAmqpClient/Util.h

Addressing several issues that prevented the build:
- `Util.h` definitions didn't take into account the static library case. A new preprocessor definition was added and propagated to avoid `__declspec` statements on the static case.
-  CMake static library strategy doesn't allow intermediate merging (to avoid duplications surely) and forces the static dependencies to be propagated.
- Dynamic linking to a static library doesn't make sense unless the dynamic library is a system/runtime one.

Fixing windows static libraries

---

src/BasicMessage.cpp

The library currently claims support for boost 1.47, which does not have
the boost::optional::value API, which BasicProperties has used.
Fixes: #345
Signed-off-by: GitHub <noreply@github.com>

Use older boost::optional::get API.
